from django.urls import path

from .admin_portal_views import (
    admin_class_create,
    admin_class_edit,
    admin_class_list,
    admin_dashboard,
    admin_login,
    admin_logout,
    admin_parent_detail,
    admin_parent_list,
    admin_parent_reset_password,
    admin_staff_create,
    admin_staff_list,
    admin_staff_reset_password,
    admin_student_assign_class,
    admin_student_list,
)


app_name = "school_admin"

urlpatterns = [
    path(
        "login/",
        admin_login,
        name="login",
    ),
    path(
        "logout/",
        admin_logout,
        name="logout",
    ),
    path(
        "",
        admin_dashboard,
        name="dashboard",
    ),
    path(
        "parents/",
        admin_parent_list,
        name="parent_list",
    ),
    path(
        "parents/<int:parent_id>/",
        admin_parent_detail,
        name="parent_detail",
    ),
    path(
        "parents/<int:parent_id>/reset-password/",
        admin_parent_reset_password,
        name="parent_reset_password",
    ),
    path(
        "staff/",
        admin_staff_list,
        name="staff_list",
    ),
    path(
        "staff/create/",
        admin_staff_create,
        name="staff_create",
    ),
    path(
        "staff/<int:staff_id>/reset-password/",
        admin_staff_reset_password,
        name="staff_reset_password",
    ),
    path(
        "classes/",
        admin_class_list,
        name="class_list",
    ),
    path(
        "classes/create/",
        admin_class_create,
        name="class_create",
    ),
    path(
        "classes/<int:class_id>/edit/",
        admin_class_edit,
        name="class_edit",
    ),
    path(
        "students/",
        admin_student_list,
        name="student_list",
    ),
    path(
        "students/<int:student_id>/assign-class/",
        admin_student_assign_class,
        name="student_assign_class",
    ),
]
