from django.urls import path

from .admin_portal_views import (
    admin_class_create,
    admin_class_edit,
    admin_class_list,
    admin_dashboard,
    admin_foundation_create,
    admin_foundation_delete,
    admin_foundation_detail,
    admin_foundation_edit,
    admin_foundation_list,
    admin_foundation_reset_password,
    admin_foundation_student_add,
    admin_foundation_student_remove,
    admin_login,
    admin_logout,
    admin_parent_detail,
    admin_parent_delete,
    admin_parent_edit,
    admin_parent_list,
    admin_parent_reset_password,
    admin_performance_create,
    admin_performance_delete,
    admin_performance_edit,
    admin_performance_list,
    admin_staff_create,
    admin_staff_delete,
    admin_staff_edit,
    admin_staff_list,
    admin_staff_reset_password,
    admin_student_assign_class,
    admin_student_list,
)


app_name = "school_admin"

urlpatterns = [
    path(
        "login/",
        admin_login,
        name="login",
    ),
    path(
        "logout/",
        admin_logout,
        name="logout",
    ),
    path(
        "",
        admin_dashboard,
        name="dashboard",
    ),
    path(
        "foundations/",
        admin_foundation_list,
        name="foundation_list",
    ),
    path(
        "foundations/create/",
        admin_foundation_create,
        name="foundation_create",
    ),
    path(
        "foundations/<int:foundation_id>/",
        admin_foundation_detail,
        name="foundation_detail",
    ),
    path(
        "foundations/<int:foundation_id>/edit/",
        admin_foundation_edit,
        name="foundation_edit",
    ),
    path(
        "foundations/<int:foundation_id>/delete/",
        admin_foundation_delete,
        name="foundation_delete",
    ),
    path(
        "foundations/<int:foundation_id>/reset-password/",
        admin_foundation_reset_password,
        name="foundation_reset_password",
    ),
    path(
        "foundations/<int:foundation_id>/students/add/",
        admin_foundation_student_add,
        name="foundation_student_add",
    ),
    path(
        "foundation-students/<int:link_id>/remove/",
        admin_foundation_student_remove,
        name="foundation_student_remove",
    ),
    path(
        "performance/",
        admin_performance_list,
        name="performance_list",
    ),
    path(
        "performance/create/",
        admin_performance_create,
        name="performance_create",
    ),
    path(
        "performance/<int:record_id>/edit/",
        admin_performance_edit,
        name="performance_edit",
    ),
    path(
        "performance/<int:record_id>/delete/",
        admin_performance_delete,
        name="performance_delete",
    ),
    path(
        "parents/",
        admin_parent_list,
        name="parent_list",
    ),
    path(
        "parents/<int:parent_id>/",
        admin_parent_detail,
        name="parent_detail",
    ),
    path(
        "parents/<int:parent_id>/edit/",
        admin_parent_edit,
        name="parent_edit",
    ),
    path(
        "parents/<int:parent_id>/delete/",
        admin_parent_delete,
        name="parent_delete",
    ),
    path(
        "parents/<int:parent_id>/reset-password/",
        admin_parent_reset_password,
        name="parent_reset_password",
    ),
    path(
        "staff/",
        admin_staff_list,
        name="staff_list",
    ),
    path(
        "staff/create/",
        admin_staff_create,
        name="staff_create",
    ),
    path(
        "staff/<int:staff_id>/edit/",
        admin_staff_edit,
        name="staff_edit",
    ),
    path(
        "staff/<int:staff_id>/delete/",
        admin_staff_delete,
        name="staff_delete",
    ),
    path(
        "staff/<int:staff_id>/reset-password/",
        admin_staff_reset_password,
        name="staff_reset_password",
    ),
    path(
        "classes/",
        admin_class_list,
        name="class_list",
    ),
    path(
        "classes/create/",
        admin_class_create,
        name="class_create",
    ),
    path(
        "classes/<int:class_id>/edit/",
        admin_class_edit,
        name="class_edit",
    ),
    path(
        "students/",
        admin_student_list,
        name="student_list",
    ),
    path(
        "students/<int:student_id>/assign-class/",
        admin_student_assign_class,
        name="student_assign_class",
    ),
]
