# Generated by Django 6.0.5 on 2026-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='CodeCamp Innovation Hub', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('auto_email_notifications', models.BooleanField(default=True)),
                ('auto_whatsapp_popup', models.BooleanField(default=False)),
                ('attendance_notifications_enabled', models.BooleanField(default=True)),
                ('parent_portal_enabled', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
