# Generated by Django 6.0.5 on 2026-06-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_class_name_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
