# Generated by Django 6.0.5 on 2026-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentparent_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Pastor', 'Pastor'), ('Chief', 'Chief'), ('Alhaji', 'Alhaji')], max_length=20),
        ),
    ]
