# Generated by Django 6.0.5 on 2026-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_parent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='receive_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
