# Generated by Django 6.0.5 on 2026-08-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_parent_account_state_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target', models.CharField(choices=[('ALL', 'All Students'), ('CLASS', 'Specific Class')], default='ALL', max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('publish_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['full_name']},
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_number'], name='students_pa_phone_n_d89417_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['full_name'], name='students_pa_full_na_2b3a01_idx'),
        ),
    ]
