# Generated by Django 6.0.5 on 2026-08-05 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_announcement_teaching_class_student_teaching_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('must_change_password', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='students_fo_email_fdd3f9_idx'), models.Index(fields=['name'], name='students_fo_name_88cc31_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='performance/')),
                ('visible_to_foundations', models.BooleanField(default=True)),
                ('recorded_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='students.student')),
                ('teaching_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_records', to='students.teachingclass')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFoundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_note', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.foundation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundation_links', to='students.student')),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('foundation', 'student'), name='unique_foundation_student_link')],
            },
        ),
    ]
