# Generated by Django 6.0.5 on 2026-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_foundation_performancerecord_studentfoundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='integration_key',
            field=models.CharField(blank=True, db_index=True, help_text='External registration key used to prevent duplicate students from integration retries.', max_length=120, null=True, unique=True),
        ),
    ]
